name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  osv_scanner:
     name: Vulnerability scanning
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-go@v4
         with:
           go-version: '1.21.1'
       - run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
       - name: Scanning
         run: osv-scanner -r .